version: '3.8'
services:
  #chapanda-website-service:
  #  build:
  #    context: ./
  #    dockerfile: ./Dockerfile
  #  depends_on:
  #    - chapanda-mysql-container
  #    - chapanda-redis-container
  #    - chapanda-minio-container
  #  ports:
  #    - 8084:8084
  #  networks:
  #    - common-network
#
  #chapanda-mysql-container:
  #  image: docker.1ms.run/library/mysql
  #  volumes:
  #    - ~/chapanda/docker-volume/chapanda-mysql:/var/lib/mysql
  #  environment:
  #    MYSQL_DATABASE: chapanda-website-database
  #    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #  ports:
  #    - 3306:3306
  #  networks:
  #    - common-network
#
  #chapanda-redis-container:
  #  image: docker.1ms.run/library/redis
  #  volumes:
  #    - ~/chapanda/docker-volume/chapanda-redis:/data
  #  environment:
  #    REDIS_PASSWORD: ${REDIS_ROOT_PASSWORD}
  #  ports:
  #    - 6379:6379
  #  networks:
  #    - common-network
#
  #chapanda-minio-container:
  #  image: bitnami/minio:latest
  #  user: "root:root"
  #  command: server /bitnami/minio/data --console-address ":9001"
  #  volumes:
  #    - ~/chapanda/docker-volume/chapanda-minio:/bitnami/minio/data
  #  environment:
  #    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #  ports:
  #    - 9000:9000
  #    - 9001:9001
  #  networks:
  #    - common-network

  chapanda-nginx-container:
    image: docker.1ms.run/library/nginx:stable-alpine # 指定服务镜像
    container_name: chapanda-nginx-container # 容器名称
    restart: always # 重启方式
    ports: # 映射端口
      - "8000:8000"
      - "721:721"
    volumes: # 挂载数据卷
      - ~/chapanda/docker-volume/chapanda-nginx/conf.d:/etc/nginx/conf.d
      - ~/chapanda/docker-volume/chapanda-nginx/logs:/var/log/nginx
      - ~/chapanda/docker-volume/chapanda-nginx/cert:/etc/nginx/cert
    depends_on: # 启动顺序
      - chapanda-website-service
networks:
  common-network:
    driver: bridge
