version: '3.8'
services:
  chapanda-website-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - chapanda-mysql-container
      - chapanda-redis-container
      - chapanda-minio-container
    ports:
      - 8084:8084
    networks:
      - common-network
    container_name: chapanda-website-service # 容器名称

  chapanda-mysql-container:
    image: docker.1ms.run/library/mysql
    container_name: chapanda-mysql-container # 容器名称
    volumes:
      - ~/chapanda/docker-volume/chapanda-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chapanda-website-database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - common-network

  chapanda-redis-container:
    image: docker.1ms.run/library/redis
    container_name: chapanda-redis-container # 容器名称
    volumes:
      - ~/chapanda/docker-volume/chapanda-redis:/data
    environment:
      REDIS_PASSWORD: ${REDIS_ROOT_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - common-network

  chapanda-minio-container:
    image: bitnami/minio:latest
    container_name: chapanda-minio-container # 容器名称
    user: "root:root"
    command: server /bitnami/minio/data --console-address ":9001"
    volumes:
      - ~/chapanda/docker-volume/chapanda-minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - common-network

  chapanda-nginx-container:
    image: docker.1ms.run/library/nginx:stable-alpine # 指定服务镜像
    container_name: chapanda-nginx-container # 容器名称
    restart: always # 重启方式
    user: "root:root"
    environment:
      TZ: Asia/Shanghai
    ports: # 映射端口
      - "8000:8000"
      - "721:721"
      - "80:80"
      - "443:443" # https 端口，妈的不用这个访问不到
    volumes: # 挂载数据卷
      - /etc/localtime:/etc/localtime  # 宿主机时间文件
      - /etc/timezone:/etc/timezone    # 宿主机时区文件
      - ~/chapanda/docker-volume/chapanda-nginx/logs:/var/log/nginx
      - ~/chapanda/docker-volume/chapanda-nginx/cert:/etc/nginx/cert
      # 注意下面两个是文件
      - ~/chapanda/docker-volume/chapanda-nginx/pid:/var/run/nginx.pid
      - ~/chapanda/docker-volume/chapanda-nginx/nginx.conf:/etc/nginx/nginx.conf
    command: >
      /bin/sh -c "
        ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime
        && echo $$TZ > /etc/timezone
        && exec nginx -g 'daemon off;'"
    depends_on: # 启动顺序
      - chapanda-website-service
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
